### ISSUE TITLE
Create All-in-one script for pipeline

### ISSUE THREAD

**Issue by vincekyi** [UCLA-BD2K/AztecRetrieval#16]
Create all-in-one script that downloads the PDFs, extracts metadata from PDF using GROBID, enrich using APIs, and insert into Solr. Each component should be modularized (1. Get papers from Journal (Download PDFs if needed), 2. Classify publication, 3. Extract metadata from PDF & enrich, 4. Insert metadata into Solr)

**Comment by Singularity9971** [comment]
Download script separate for now.
