### ISSUE TITLE
Extract Metadata from Publication

### ISSUE THREAD

**Issue by vincekyi** [UCLA-BD2K/AztecRetrieval#3]
Using Grobid, extract metadata from the PDF.
Metadata includes tools name, description (abstract), links, source code links, technologies, grant/funding information, authors, and affiliations.

**Comment by Singularity9971** [comment]
Mostly Working-
Name
Description
Links
Authors
Affiliations

Sometimes Working-
Grant/funding information
Source Code links

Not Working-
Technologies
