### ISSUE TITLE
Using Pubmed API

### ISSUE THREAD

**Issue by vincekyi** [UCLA-BD2K/AztecRetrieval#5]
Using the Pubmed API, retrieve the following information:
PMID (Pubmed ID), Journal Name, DOI, affiliation, Author, Publication title.

Example: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=27402908&rettype=xml

**Comment by xxlltm** [comment]
There is another Pubmed API that can convert DOIs into other types of the IDs, such as PMID, PMCID and Manuscript ID.  Combined with the first API, it may help to supplement the metadata of tools (with doi) in our current database.
Example:
https://www.ncbi.nlm.nih.gov/pmc/utils/idconv/v1.0/?ids=10.1038/nbt.2862&idtype=doi&format=json
